import Head from 'next/head'
import QuestaoModel from '../../model/questao'
import { useEffect, useState } from 'react'
import Questionario from '../../components/Questionario'
import { useRouter } from 'next/router'


const BASE_URL = 'http://localhost:3000/api'

export default function Home() {
  const router = useRouter()

  const [idsDasQuestoes, setIdsDasQuestoes] = useState<number[]>([])
  const [questao, setQuestao] = useState<QuestaoModel>()
  const [respostasCertas, setRespostasCertas] = useState<number>(0)
  const [quizIniciado, setQuizIniciado] = useState(false)

  async function loadIds() {
    const resp = await fetch(`${BASE_URL}/questionario`)
    const idsDasQuestoes = await resp.json()
    setIdsDasQuestoes(idsDasQuestoes)
  }

  async function loadQuestion(idQuestao: number) {
    const resp = await fetch(`${BASE_URL}/questoes/${idQuestao}`)
    const json = await resp.json()
    const novaQuestao = QuestaoModel.fromObject(json)
    setQuestao(novaQuestao)
  }

  useEffect(() => {
    loadIds()
  }, [])

  useEffect(() => {
    if (quizIniciado && idsDasQuestoes.length > 0) {
      loadQuestion(idsDasQuestoes[0])
    }
  }, [idsDasQuestoes, quizIniciado])

  function onResponse(questaoRespondida: QuestaoModel) {
    setQuestao(questaoRespondida)
    setRespostasCertas(respostasCertas + (questaoRespondida.acertou ? 1 : 0))
  }

  function idProximaPergunta() {
    if (questao) {
      const proximoIndice = idsDasQuestoes.indexOf(questao.id) + 1
      return idsDasQuestoes[proximoIndice]
    }
  }

  function irPraProximoPasso() {
    const proximoId = idProximaPergunta()
    proximoId ? irPraProximaQuestao(proximoId) : finalizar()
  }

  function irPraProximaQuestao(proximoId: number) {
    loadQuestion(proximoId)
  }

  function finalizar() {
    router.push({
      pathname: '/resultado',
      query: {
        total: idsDasQuestoes.length,
        certas: respostasCertas
      }
    })
  }

  function iniciarQuiz() {
    setQuizIniciado(true)
  }

  return (
    <>
      <Head>
        <title>JOMAP 2023 - Big Data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="container">
      <h1>PROJETO BIGDATA - QUIZ</h1>
      <h2>Respondam ao nosso questionário sobres áreas de:</h2>
      <h4> Linguagens e suas Tecnologias;
Matemática e suas Tecnologias *

Ciências Humanas e Sociais Aplicadas * Ciências da Natureza e suas Tecnologias </h4>
          {!quizIniciado ? (
            <button onClick={iniciarQuiz}>Iniciar Quiz</button>
          ) : questao ? (
            <Questionario
              questao={questao}
              ultima={idProximaPergunta() === undefined}
              onResponse={onResponse}
              irPraProximoPasso={irPraProximoPasso}
            />
          ) : null}
        </div>
      </main>
      <style jsx>{`
        .container {
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          height: 100vh;
          text-align: center;
        }

        .title {
          font-size: 32px;
          margin-bottom: 16px;
        }

        .subtitle {
          font-size: 18px;
          margin-bottom: 24px;
        }

        .start-button {
          padding: 10px 20px;
          font-size: 18px;
          background-color: #f0f0f0;
          border: none;
          border-radius: 4px;
          cursor: pointer;
        }
      `}</style>
    </>
  )
}
